### ISSUE TITLE
Control implementations don't do error handling correctly

### ISSUE THREAD

**Issue by anacrolix** [libp2p/go-reuseport#101]
The windows implementation clobbers the error returned from SetsockoptInt with the result of the Control method call. https://github.com/libp2p/go-reuseport/blob/194b8a8db9d5fea11e3c6ca1ed8cfa1dc07adc8d/control_windows.go#L10

The unix implementation doesn't handle the error returned from the Control method call at all. https://github.com/libp2p/go-reuseport/blob/194b8a8db9d5fea11e3c6ca1ed8cfa1dc07adc8d/control_unix.go#L13

**Comment by marten-seemann** [comment]
Want to submit a patch?
