### ISSUE TITLE
[Question] Not clear implementation of Available()

### ISSUE THREAD

**Issue by g41797** [libp2p/go-reuseport#114]
```go
// Available returns whether or not SO_REUSEPORT or equivalent behaviour is
// available in the OS.
func Available() bool {
	return true
}
```
So for every os _*SO_REUSEPORT*_ is available

But for windows (see below) it does not exist
```go
func Control(network, address string, c syscall.RawConn) (err error) {
	controlErr := c.Control(func(fd uintptr) {
		err = windows.SetsockoptInt(windows.Handle(fd), windows.SOL_SOCKET, windows.SO_REUSEADDR, 1)
	})
	if controlErr != nil {
		err = controlErr
	}
	return
}
```

do you accept PRs?

**Comment by willscott** [comment]
Yes - PRs welcome!

I wonder if `Available` is used anywhere? code search doesn't surface any obvious uses of it, so it may just be a left over remnant.

**Comment by g41797** [comment]
I'd like to create N udp servers for the same port
Because on windows this functionality does not exist I should to call Available
in order to write portable code  
Looks like Available will call control.available()
Also looks strange that for reuseaddr and reuseport returns 1 bool
your turn

**Comment by marten-seemann** [comment]
> I wonder if `Available` is used anywhere? code search doesn't surface any obvious uses of it, so it may just be a left over remnant.

It is here: https://github.com/libp2p/go-libp2p/blob/4e2a16dd3f4f980bf9429572b3d2aed885594ec4/p2p/net/reuseport/listen.go#L46-L48

**Comment by g41797** [comment]
- leave Available as-is and add AvailReuseAddr & AvailReusePort or
- func Available() (reuseaddr, reuseport bool)

**Comment by marten-seemann** [comment]
> btw what is the reason to require go 1.20?

It's our release policy to support the two most recent Go releases.



> * leave Available as-is and add AvailReuseAddr & AvailReusePort or
> * func Available() (reuseaddr, reuseport bool)

What's the use case for splitting it into two?

**Comment by g41797** [comment]
so something like:
```go
// Available returns whether or not SO_REUSEADDR and SO_REUSEPORT are available in the OS.
func Available() (reuseaddr, reuseport bool) {
	return available()
}
```

**Comment by marten-seemann** [comment]
Again, what's the use case? What problem are you trying to solve?

**Comment by g41797** [comment]
because SO_REUSEADDR is not enough:
"..traditional SO_REUSEADDR socket option already allows multiple UDP sockets to be bound to, and accept datagrams on, the same UDP port. However, by contrast with SO_REUSEPORT, SO_REUSEADDR does not prevent port hijacking and does not distribute datagrams evenly across the receiving threads" [The SO_REUSEPORT socket option](https://lwn.net/Articles/542629/)

**Comment by marten-seemann** [comment]
That's not what we're using reuseport though. We only use it for TCP, to be able to run a listener and outgoing connections on the same port. I don't think we should get into the specifics of SO_REUSEPORT and SO_REUSEADDR, as they're highly platform specific.

**Comment by g41797** [comment]
no problem
you got star and new fork
