### ISSUE TITLE
panic: address already in use 

### ISSUE THREAD

**Issue by krisoul** [libp2p/go-reuseport#13]
I tried your demo, but still appeared this problem: "address already in use"

go version go1.4.2 linux/amd64
CentOS release 6.6 (Final)
Linux version 2.6.32-504.el6.x86_64

why?

**Comment by marcelki** [comment]
You've got a pretty old kernel version.
The *SO_REUSEPORT* option was introduced in the **3.9 kernel**.

**Comment by EverChris** [comment]
I guessed so, thanks anyway.

**Comment by Stebalien** [comment]
Anyways, I believe we now correctly *test* for support instead of simply panicing.
