### ISSUE TITLE
available_unix.go is over complex

### ISSUE THREAD

**Issue by tv42** [libp2p/go-reuseport#3]
Belated drive-by code review.

It looks like available_unix.go could be replaced with

``` go
var (
    hasReusePort bool
    didReusePort sync.Once
)

func checkReusePort() {
    ...
    hasReusePort = whatever
}

func available() bool {
    didReusePort.Do(checkReusePort)
    return hasReusePort
}
```

**Comment by jbenet** [comment]
you're right-- the atomic thing is silly. though-- is Do equally fast? probably...

**Comment by tv42** [comment]
Faster. It only needs one atomic load on the fast path, because fast path guarantees hasReusePort has been set.
https://golang.org/src/sync/once.go?s=1139:1166#L25

**Comment by jbenet** [comment]
great! :+1:
