### ISSUE TITLE
The constant SO_REUSEPORT is still missing in Linux/386 and amd64. 

### ISSUE THREAD

**Issue by hayarobi** [libp2p/go-reuseport#49]
It's related to #36 and #41 . 
I got a compile error when build codes in my linux. 
I found related issue in golang official; https://github.com/golang/go/issues/23696 

Here is my Ubuntu system. I check go-1.10 and go-1.9.
adm@ubuntu1604:/usr/lib/go-1.10/src$ uname -a
Linux ubuntu1604 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

adm@ubuntu1604:/usr/lib/go-1.10/src$ grep -R SO_REUSEPORT * | sort
net/net_test.go: // enabling SO_REUSEPORT option such as Linux,
net/sockopt_bsd.go: return os.NewSyscallError("setsockopt", syscall.SetsockoptInt(s, syscall.SOL_SOCKET, syscall.SO_REUSEPORT, 1))
syscall/net_nacl.go: SO_REUSEPORT
syscall/zerrors_darwin_386.go: SO_REUSEPORT = 0x200
syscall/zerrors_darwin_amd64.go: SO_REUSEPORT = 0x200
syscall/zerrors_darwin_arm64.go: SO_REUSEPORT = 0x200
syscall/zerrors_darwin_arm.go: SO_REUSEPORT = 0x200
syscall/zerrors_dragonfly_amd64.go: SO_REUSEPORT = 0x200
syscall/zerrors_freebsd_386.go: SO_REUSEPORT = 0x200
syscall/zerrors_freebsd_amd64.go: SO_REUSEPORT = 0x200
syscall/zerrors_freebsd_arm.go: SO_REUSEPORT = 0x200
syscall/zerrors_linux_arm64.go: SO_REUSEPORT = 0xf
syscall/zerrors_linux_mips64.go: SO_REUSEPORT = 0x200
syscall/zerrors_linux_mips64le.go: SO_REUSEPORT = 0x200
syscall/zerrors_linux_mips.go: SO_REUSEPORT = 0x200
syscall/zerrors_linux_mipsle.go: SO_REUSEPORT = 0x200
syscall/zerrors_linux_ppc64.go: SO_REUSEPORT = 0xf
syscall/zerrors_linux_ppc64le.go: SO_REUSEPORT = 0xf
syscall/zerrors_linux_s390x.go: SO_REUSEPORT = 0xf
syscall/zerrors_netbsd_386.go: SO_REUSEPORT = 0x200
syscall/zerrors_netbsd_amd64.go: SO_REUSEPORT = 0x200
syscall/zerrors_netbsd_arm.go: SO_REUSEPORT = 0x200
syscall/zerrors_openbsd_386.go: SO_REUSEPORT = 0x200
syscall/zerrors_openbsd_amd64.go: SO_REUSEPORT = 0x200
syscall/zerrors_openbsd_arm.go: SO_REUSEPORT = 0x200

**Comment by Stebalien** [comment]
We use the constants defined in golang.org/x/sys/unix. You may need to update that package.

What's the exact error you're seeing?

**Comment by hayarobi** [comment]
@Stebalien  It was my fault. I misunderstood the compile error message.

**Comment by Stebalien** [comment]
Np. Our rule with libp2p is: when in doubt, blame reuseport.
