### ISSUE TITLE
Are you planning on adding tfo(tcp fast open)

### ISSUE THREAD

**Issue by jiangth122** [libp2p/go-reuseport#51]
do you plan to develop a new version of TFO to support golang？It is really excellent to reduce the time of TCP three-time handshake ，but don‘t support golang still now，and golang is a  popular  computer language in recent years。thanks

**Comment by Stebalien** [comment]
Really, we're planning on mostly deprecating this package. With go 1.11, you can set socket options using by setting a `Control` function in either a `ListenConfig` or a `Dialer`.

In your case, you'll want to make a custom `ListenConfig` and then use `unix.SetSockopt(...)` to set the TCP fast-open socket option. You probably don't need this package and *definitely* shouldn't use it unless you do.
