### ISSUE TITLE
win not work

### ISSUE THREAD

**Issue by ladixiu** [libp2p/go-reuseport#53]
![image](https://user-images.githubusercontent.com/43605070/49373209-27a2a580-f738-11e8-8d20-15971ea4d173.png)

i want use nat ,build a connect for two work's net 。 my user most use win .....

**Comment by Stebalien** [comment]
Unfortunately, this library doesn't *currently* support windows. When finished, https://github.com/libp2p/go-reuseport/pull/50 will fix that but there's currently nobody working on that PR.
