### ISSUE TITLE
Bug-Report[reuse-port]fail to bind port in some device

### ISSUE THREAD

**Issue by serfend** [libp2p/go-reuseport#95]
## in win7 with services VNCServer running on 5900,run following will sometimes get error.
```go

import (
	"fmt"
	"log"
	"net"
	reuseport "github.com/libp2p/go-reuseport"
)

func reuse(options *Options) (net.Conn, string) {
	listenAddr := fmt.Sprintf("%s:%s", options.ReuseHost, options.ReusePort)

	listener, err := reuseport.Listen("tcp", listenAddr)
	if err != nil {
		log.Fatalf("[*] Error occured: %s", err.Error()) // HERE throw error
	}
}
```
`bind: attempt was made to access a socket in a way forbidden by its access permissions`
i tested in 2 different devices which one successfully listen and one fail.

**Comment by marten-seemann** [comment]
Are you trying to bind to a port that another application is already listening on?

**Comment by serfend** [comment]
oh i see , port reuse is base on service which listening on port INACTIVE (tcp establish) . or else will not able to listen reuse.

**Comment by marten-seemann** [comment]
You can't use reuseport to steal from an already running application, the appropriate flags have to be set when starting the listener.
